server:
  prot: 9801
spring:
  application:
    name: systemanage
  datasource:
    #url: jdbc:log4jdbc:mysql://192.168.1.4:3306/dyitp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    #username: root
    #password: pa55w()rd
    url: jdbc:log4jdbc:mysql://192.168.1.2:3306/dyitptest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy
    dbcp2:
      test-on-borrow: false
      testWhileIdle: true
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 3600000
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    jdbc: error
    jdbc.sqltiming: info
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  config: classpath:log4j2.xml

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: clientId
      clientSecret: secret
    resource:
      userInfoUri: http://192.168.1.3:8080/auth/user/info
      prefer-token-info: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.3:8011/eureka/
      
ribbon:
  eureka:
    enabled: true

https:
  port: 8443
  ssl:
    key-store: server.keystore
    key-store-pas sword: secret
    key-password: password

prod:
  configpath: config

mybatis.type-aliases-package: com.grape.model.db

mybatis.mapper-locations: classpath*:/com/grape/model/mapper/base/*.xml,classpath*:com/grape/model/mapper/external/*.xml