server:
  port: 8090
  
spring:
  application:
    name: home
  datasource:
    url: jdbc:log4jdbc:mysql://192.168.1.4:3306/dyitp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: Pa55w()rd
    driver-class-name: net.sf.log4jdbc.DriverSpy
  redis:
    host: 192.168.1.4
    database: 0
    password: grape
    
  jpa:
    hibernate:
       ddl-auto: update
       
  mvc:
    static-path-pattern: /figure/**
  resources:
    static-locations: file:C:\Users\Administrator\Desktop\DY\DYSTP\codes\common-base\frame-home\src\main\resources\figure
  
logging:
  level:
    jdbc: error
    jdbc.sqltiming: info
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  config: classpath:log4j2.xml

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: clientId
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:8080/auth/user/info
      prefer-token-info: false

https:
  port: 8443
  ssl:
    key-store: server.keystore
    key-store-password: secret
    key-password: password    

prod:
  configpath: config

mybatis.type-aliases-package: com.grape.model.db
 
mybatis.mapper-locations: classpath*:/com/grape/model/mapper/base/*.xml,classpath*:com/grape/model/mapper/external/*.xml  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 
    lease-expiration-duration-in-seconds: 60  