server:
  port: 8088
  context-path: /
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://22.145.26.104:3306/commondb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: commonuser
    password: pa55w()rd
    driver-class-name: net.sf.log4jdbc.DriverSpy
  jpa:
    hibernate:
       ddl-auto: update
logging:
  level:
    jdbc: error
    jdbc.sqltiming: info
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: clientId
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:9999/user/info
      prefer-token-info: false

https:
  port: 8443
  ssl:
    key-store: server.keystore
    key-store-password: secret
    key-password: password    

prod:
  configpath: config