server:
  port: 8011                    
  #ssl:
     #client-auth: want
     #key-store: classpath:keystore.jks
     #key-store-password: 123456
     #keyStoreType: JKS
     #key-alias: certificatekey

eureka:       
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8011/
  server:
     enable-self-preservation: false
     eviction-interval-timer-in-ms: 60000

logging:
  level:
    jdbc: error
    jdbc.sqltiming: info
    org.springframework.security: INFO
    org.springframework.web: INFO
  config: classpath:log4j2.xml
