server:
  port: 9999
spring:
  application:
    name: auth
  datasource:
    url: jdbc:log4jdbc:mysql://192.168.1.4:3306/dyitp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Pa55w()rd
    driver-class-name: net.sf.log4jdbc.DriverSpy
  redis:
    host: 192.168.1.4
    database: 4
    password: grape
  jpa:
    hibernate:
       ddl-auto: update
logging:
  level:
    jdbc: error
    jdbc.sqltiming: info
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  config: classpath:log4j2.xml
    
https:
  port: 8443
  ssl:
    key-store: server.keystore
    key-store-password: secret
    key-password: password    


prod:
  configpath: config
  
mybatis.type-aliases-package: com.grape.model.db
 
mybatis.mapper-locations: classpath*:/com/grape/model/mapper/base/*.xml,classpath*:com/grape/model/mapper/external/*.xml
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 
    lease-expiration-duration-in-seconds: 60  